import { test, expect, type Download } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import yauzl from "yauzl";

// End-to-end smoke test for the shipped ESM bundle.
//
// Flow under test: select a folder in `demo/compress.html` -> the demo calls
// the real `dist/jszipp.mjs` `ZipWriter` in the browser -> Blob -> download. The
// produced archive is then re-read with yauzl (an INDEPENDENT reader) so a green
// run means the browser-generated bytes are a structurally valid ZIP, not merely
// something JSZipp can read back. This is the only automated check that exercises
// the built bundle in a real engine end to end. See docs/testing.md.

const DEMO = "/demo/compress.html";

// The demo's file input is `webkitdirectory`, so a directory must be selected.
// Chromium prefixes each entry with the directory's basename, hence "fixtures/".
const FIXTURES_DIR = fileURLToPath(new URL("./fixtures", import.meta.url));
const HELLO = "Hello from the JSZipp e2e smoke test.\n";
const NOTES = "second file\nwith two lines\n";

type ZipContents = Record<string, { method: number; text: string }>;

// Read a ZIP buffer with yauzl and return each entry's compression method and
// decoded text. Independent of JSZipp on purpose.
function readZipWithYauzl(buffer: Buffer): Promise<ZipContents> {
  return new Promise((resolve, reject) => {
    yauzl.fromBuffer(buffer, { lazyEntries: true }, (err, zip) => {
      if (err || !zip) return reject(err ?? new Error("no zipfile"));
      const out: ZipContents = {};
      zip.on("error", reject);
      zip.on("entry", (entry) => {
        if (/\/$/.test(entry.fileName)) {
          zip.readEntry();
          return;
        }
        zip.openReadStream(entry, (streamErr, stream) => {
          if (streamErr || !stream) return reject(streamErr ?? new Error("no stream"));
          const chunks: Buffer[] = [];
          stream.on("data", (c) => chunks.push(c as Buffer));
          stream.on("end", () => {
            out[entry.fileName] = {
              method: entry.compressionMethod,
              text: Buffer.concat(chunks).toString("utf8")
            };
            zip.readEntry();
          });
          stream.on("error", reject);
        });
      });
      zip.on("end", () => resolve(out));
      zip.readEntry();
    });
  });
}

async function downloadToBuffer(download: Download): Promise<Buffer> {
  const path = await download.path();
  if (!path) throw new Error("download produced no file path");
  return readFile(path);
}

test.beforeEach(async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", (e) => errors.push(String(e)));
  await page.goto(DEMO);
  // The demo bootstraps by dynamically importing the bundle, then flags itself
  // ready. Waiting on this avoids racing the change/click listeners.
  await expect(page.locator("body")).toHaveAttribute("data-ready", "true");
  expect(errors, "no page errors while loading the demo bundle").toEqual([]);
});

test("compresses a selected folder into a valid ZIP (balanced/deflate)", async ({ page }) => {
  await page.setInputFiles("#file-input", FIXTURES_DIR);

  // The change handler ran: counters update and the action enables.
  await expect(page.locator("#file-count")).toHaveText("2");
  await expect(page.locator("#input-size")).not.toHaveText("0 B");
  await expect(page.locator("#compress")).toBeEnabled();

  await page.click("#compress");

  // Success is signalled by the status going green and the ZIP size filling in.
  await expect(page.locator("#status.ok")).toContainText("Created compressed-files.zip.");
  await expect(page.locator("#zip-size")).not.toHaveText("-");

  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.click("#download")
  ]);
  expect(download.suggestedFilename()).toBe("compressed-files.zip");

  const buffer = await downloadToBuffer(download);
  expect(buffer.length).toBeGreaterThan(0);

  // Independent reader confirms the browser-produced bytes are a real ZIP.
  const contents = await readZipWithYauzl(buffer);
  expect(Object.keys(contents).sort()).toEqual(["fixtures/hello.txt", "fixtures/notes.txt"]);
  expect(contents["fixtures/hello.txt"].text).toBe(HELLO);
  expect(contents["fixtures/notes.txt"].text).toBe(NOTES);
  // Balanced level on compressible text should deflate (method 8), not store.
  expect(contents["fixtures/hello.txt"].method).toBe(8);
});

test("store level keeps entries uncompressed (method 0)", async ({ page }) => {
  await page.setInputFiles("#file-input", FIXTURES_DIR);
  await expect(page.locator("#file-count")).toHaveText("2");

  // The radio is visually hidden behind its styled label, so check by force; the
  // demo only reads `input[name='level']:checked` when Compress is clicked.
  await page.check("input[name='level'][value='0']", { force: true });
  await page.click("#compress");
  await expect(page.locator("#status.ok")).toContainText("Created");

  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.click("#download")
  ]);
  const contents = await readZipWithYauzl(await downloadToBuffer(download));

  expect(contents["fixtures/hello.txt"].text).toBe(HELLO);
  expect(contents["fixtures/hello.txt"].method).toBe(0);
  expect(contents["fixtures/notes.txt"].method).toBe(0);
});

test("loads the built worker plugin and real module worker script in Chromium", async ({ page }) => {
  await page.goto("/demo/compress.html");

  const archiveBytes = await page.evaluate(async () => {
    const [{ ZipWriter }, { createWorkerBackend }] = await Promise.all([
      import("/dist/jszipp.mjs"),
      import("/dist/jszipp.worker-plugin.mjs")
    ]);

    const worker = createWorkerBackend({
      fallback: false,
      minSize: 0,
      workerSource: () => new Worker("/dist/jszipp.worker.mjs", { type: "module" })
    });

    try {
      const writer = new ZipWriter({ outputAs: "uint8array", worker });
      await writer.add({ path: "worker.txt", data: "worker path ok\n".repeat(256) });
      return Array.from(await writer.close());
    } finally {
      worker.terminate();
    }
  });

  const contents = await readZipWithYauzl(Buffer.from(archiveBytes));
  expect(Object.keys(contents)).toEqual(["worker.txt"]);
  expect(contents["worker.txt"].text).toBe("worker path ok\n".repeat(256));
  expect(contents["worker.txt"].method).toBe(8);
});

test("clear resets the demo state", async ({ page }) => {
  await page.setInputFiles("#file-input", FIXTURES_DIR);
  await expect(page.locator("#file-count")).toHaveText("2");

  await page.click("#clear");

  await expect(page.locator("#file-count")).toHaveText("0");
  await expect(page.locator("#compress")).toBeDisabled();
  await expect(page.locator("#download")).toBeDisabled();
  await expect(page.locator("#zip-size")).toHaveText("-");
});
